image:
  imageRegistry: ghcr/cosmo-tech
  repository: cosmotech-redis
  tag: latest
commonConfiguration: |-
  loadmodule /opt/bitnami/redis/modules/redisgraph.so
  loadmodule /opt/bitnami/redis/modules/redistimeseries.so
  loadmodule /opt/bitnami/redis/modules/rejson.so
