image:
  registry: ghcr.io
  repository: cosmo-tech/cosmotech-redis
  tag: latest
commonConfiguration: |-
  loadmodule /opt/bitnami/redis/modules/redisgraph.so
  loadmodule /opt/bitnami/redis/modules/redistimeseries.so
  loadmodule /opt/bitnami/redis/modules/rejson.so
commonAnnotations: |-
  labels:
    networking/traffic-allowed: "yes"
