image:
  registry: ghcr.io
  repository: cosmo-tech/cosmotech-redis
  tag: latest
master:
  podLabels:
    networking/traffic-allowed: "yes"
replica:
  podLabels:
    networking/traffic-allowed: "yes"
commonConfiguration: |-
  repl-diskless-sync no
  stop-writes-on-bgsave-error no
  client-output-buffer-limit normal 0 0 0
  client-output-buffer-limit replica 512mb 512mb 60
  client-output-buffer-limit pubsub 32mb 8mb 60
  loadmodule /opt/bitnami/redis/modules/redisgraph.so
  loadmodule /opt/bitnami/redis/modules/redistimeseries.so DUPLICATE_POLICY LAST
  loadmodule /opt/bitnami/redis/modules/rejson.so
  loadmodule /opt/bitnami/redis/modules/redisearch.so
# Adding this part to override default values (even if volumePermissions and sysctl are disabled)
# See https://github.com/bitnami/charts/issues/35164
volumePermissions:
  enabled: false
  image:
    registry: docker.io
    repository: bitnamilegacy/os-shell
    tag: 12-debian-12-r21
sysctl:
  enabled: false
  image:
    registry: docker.io
    repository: bitnamilegacy/os-shell
    tag: 12-debian-12-r21
